#! /bin/bash
#


echo -n "Input Score : "

read score

if (( $score > 90 ))
then
	echo "Your score is great"
elif (($score > 30 ))
then 
	echo "Your score is not good"
	sleep 3
	echo "But not good"
else
	echo "what is your score"
fi

