#! /bin/bash

read first last

echo $first + $last =  $(($first + $last))

echo $first - $last = $(($first - $last))

echo $first \* $last = $(($first * $last))

echo $first / $last = $(($first / $last))


