#! /bin/bash

add ()
{
  echo $1 \+ $3 \= $(( $1 + $3 ))
}

subtract ()
{
  echo $1 \- $3 \= $(( $1 - $3 ))
}

multiply ()
{
  echo $1 \* $3 \= $(( $1 * $3 ))
}

divide ()
{
  echo $1 \/ $3 \= $(( $1 / $3 ))
}


  case $2 in 
  +)
  add $@;;
  -)
  subtract $@;;
  /)
  divide $@;;
  *)
  multiply $@;;
  esac

