#! /bin/bash

add ()
{
  echo $1 \+ $3 \= $(( $1 + $3 ))
}

subtract ()
{
  echo $1 \- $3 \= $(( $1 - $3 ))
}

multiply ()
{
  echo $1 \* $3 \= $(( $1 * $3 ))
}

divide ()
{
  echo $1 \/ $3 \= $(( $1 / $3 ))
}

select cmd in add subtract multiply divide
do
 read -p "Input :" one two three
  $cmd $one $two $three 
done


